add js/css assets only on warmup pages
FriendsOfREDAXO/cache_warmup pull request #83
Opened 2017-12-14 20:03 UTC by staabm

without this change, the `warmup.(css|js)` is included in all backend pages, so e.g. even on structure/ or similar.

while working at it I am wondering whether the styles are required at all. @schuer are you sure this files (and their contents) are still used?

2017-12-15 09:36 UTC, schuer commented
Thx @staabm. I think you’re totally right and nobody’s noticed the issue yet.

However, I cannot test your warmup PRs right now but will do a redaxo session next week something. Thx in advance!

2017-12-28 18:05 UTC, schuer requested changes
@staabm Since we require the assets on 2 pages, `cache_warmup/warmup` and `system/cache_warmup`, I’d suggest to go for something like this:

```php
if (rex::isBackend() && rex::getUser() && strpos(rex_be_controller::getCurrentPage(), 'cache_warmup') !== false) {
```

2017-12-28 19:14 UTC, staabm commented
👍here we go

2017-12-28 19:19 UTC, schuer requested changes
Comment’s wrong. Should be `cache_warmup/warmup` and `system/cache_warmup`.

2017-12-28 19:37 UTC, staabm commented
🤓

2017-12-28 20:30 UTC, schuer approved these changes

2017-12-28 20:30 UTC, merged

2017-12-28 20:30 UTC, schuer commented
🎉 thx!